apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-deployment
spec:
  selector:
    matchLabels:
      app: fib
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fib
    spec:
      containers:
      - name: fib
        image: rootdock/multi-client
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
