apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
  labels:
    component: web
spec:
  selector:
    component: web
  type: ClusterIP
  ports:
    - name: web
      port: 3000
      targetPort: 3000