apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: fib-w
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fib-w
    spec:
      containers:
      - name: fib-w
        image: stephengrider/multi-worker
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
