apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
  labels:
    component: redis
spec:
  selector:
    component: redis
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379