apiVersion: v1
kind: Service
metadata:
  name: fib-service-worker
  labels:
    app: fib-w
spec:
  selector:
    app: fib-w
  type: NodePort
  ports:
    - name: fib-w
      port: 3060
      targetPort: 3000
      nodePort: 31110

