apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    component: server
spec:
  selector:
    component: server
  type: ClusterIP
  ports:
    - name: Service
      port: 5000
      targetPort: 5000
