apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: worker
spec:
  selector:
    app: worker
  type: ClusterIP
  ports:
    - name: worker
      port: 3060
      targetPort: 3000
      