apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      component: worker
  replicas: 1
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
      - name: client
        image: rootdock/multi-worker
        ports:
        - containerPort: 3000
